/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER COOPERATIVA IDENTIFIED BY "DuocUC..2025"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER COOPERATIVA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO COOPERATIVA;
GRANT "RESOURCE" TO COOPERATIVA;
ALTER USER COOPERATIVA DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER COOPERATIVA IDENTIFIED BY "DuocUC..2025"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER COOPERATIVA QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO COOPERATIVA;
GRANT "RESOURCE" TO COOPERATIVA;
ALTER USER COOPERATIVA DEFAULT ROLE "RESOURCE"